package com.neuedu.dao;

import com.neuedu.bean.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_order
     *
     * @mbg.generated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);

    /**
     * 根据用户id和订单编号查询对应订单
     * @param userId
     * @param orderNo
     * @return
     */
    Order findOrderByUserIdAndOrderNo(@Param("userId") Integer userId, @Param("orderNo") Long orderNo);

    /**
     * 根据订单编号查询
     * @param orderNo
     * @return
     */
    Order findOrderByOrderNo(Long orderNo);

    /**
     * 查询订单(用户)
     * @param userId
     * @return
     */
    List<Order> findOrderByUserId(Integer userId);
}