package com.neuedu.dao;

import com.neuedu.bean.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfo record);

    int checkUsername(String username);

    UserInfo selectUserByUsernameAndPassword(@Param("username") String username,
                                             @Param("password") String password);
    /*校验邮箱*/
    int checkEmail(String email);

    String selectQuestionByUsername(@Param("username") String username);

    /**
     * 校验答案
     */
    int checkAnswerByUsernameAndQuestion(@Param("username") String username,
                                         @Param("question") String question,
                                         @Param("answer") String answer);

    /**
     * 根据用户名修改密码
     * @param username
     * @param passwordNew
     * @return
     */
    int updatePasswordByUsername(@Param("username") String username,
                                 @Param("password") String passwordNew);
}